name: Publish NuGet Package

on:
  workflow_dispatch:
    
jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      version: v${{steps.get-version.outputs.version}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags origin

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Get version
        id: get-version
        run: |
            version=$(dotnet build --getProperty:Version)
            echo "version=$version" >> "$GITHUB_OUTPUT"
        working-directory: MaxDon.ApimUpdater

      - name: Ensure version is correct
        run: |
          tag=v${{steps.get-version.outputs.version}}
          if [ $(git tag -l "$tag") ]; then
            echo "Error: tag $tag already exists"
            exit 1
          fi

  release-and-publish:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build package
        run: dotnet pack -c Release -o ./artifacts /p:RepositoryCommit=${{ github.sha }}

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: ${{needs.validate.outputs.version}}
          prerelease: false
          title: 'Release version ${{needs.validate.outputs.version}}'

      - name: Publish package
        run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
